-- Seed: districts
INSERT INTO districts (district_name, region_id)
SELECT d.district_name, r.region_id FROM (VALUES
  ('Ablekuma West', 'Greater Accra'),
  ('Abura Asebu Kwamankese', 'Central'),
  ('Abura/Asebu/kwamankese', 'Central'),
  ('Accra Metro', 'Greater Accra'),
  ('Ada East', 'Greater Accra'),
  ('Afadzto South', 'Volta'),
  ('Afigya Kwabre South', 'Ashanti'),
  ('Agona West Mun.', 'Central'),
  ('Ahanta West', 'Western'),
  ('Ajumako Enyan Esiam', 'Central'),
  ('Ajumako/ Enyan /Essiam', 'Central'),
  ('Akatsi North', 'Volta'),
  ('Akatsi South', 'Volta'),
  ('Akuampem North', 'Eastern'),
  ('Akwapem South', 'Eastern'),
  ('Amansie Central', 'Ashanti'),
  ('Amansie West', 'Ashanti'),
  ('Amenfi West', 'Western'),
  ('Anloga Municipal', 'Volta'),
  ('Asante Akim Central', 'Ashanti'),
  ('Asante Akim South', 'Ashanti'),
  ('Asante Akyem Central', 'Ashanti'),
  ('Ashiaman Mun', 'Greater Accra'),
  ('Asikuma Odoben Brakwa', 'Central'),
  ('Asokwa', 'Ashanti'),
  ('Assin Central Mun.', 'Central'),
  ('Assin Jakai', 'Central'),
  ('Assin North', 'Central'),
  ('Asunafo North', 'Ahafo'),
  ('Asunafo South', 'Ahafo'),
  ('Asuogyaman', 'Eastern'),
  ('Asutifi North', 'Ahafo'),
  ('Atiwa East', 'Eastern'),
  ('Atiwa West', 'Eastern'),
  ('Atwim Nwabiagya', 'Ashanti'),
  ('Atwima Kwawoma', 'Ashanti'),
  ('Atwima Mponua', 'Ashanti'),
  ('Awutu Senya West', 'Central'),
  ('Ayawaso', 'Greater Accra'),
  ('Ayawaso Central', 'Greater Accra'),
  ('Ayawaso East', 'Greater Accra'),
  ('Ayawaso East Sub Metro', 'Greater Accra'),
  ('Ayawaso South', 'Greater Accra'),
  ('Bawku East', 'Upper East'),
  ('Bawku West Mun.', 'Upper East'),
  ('Bekwai Mun.', 'Ashanti'),
  ('Bibiani Anhwiaso Bekwai', 'Western North'),
  ('Bole', 'Savannah'),
  ('Bolgatanga', 'Upper East'),
  ('Bolgatanga Mun', 'Upper East'),
  ('Bongo', 'Upper East'),
  ('Bosome Freho', 'Ashanti'),
  ('Bosome-Freho', 'Ashanti'),
  ('Bosomtwe', 'Ashanti'),
  ('Bosomtwi', 'Ashanti'),
  ('Builsa North', 'Upper East'),
  ('Cape Coast Metro', 'Central'),
  ('Cape Coast Mun', 'Central'),
  ('Central Gonja', 'Savannah'),
  ('Dafiama Busie Issa', 'Upper West'),
  ('Dayi', 'Volta'),
  ('Denkyembour', 'Eastern'),
  ('Dormaa Central', 'Bono'),
  ('Dormaa Central Mun', 'Bono'),
  ('Eask Akim Mun.', 'Eastern'),
  ('East Akim', 'Eastern'),
  ('East Gonja', 'Savannah'),
  ('East Mamprusi', 'North East'),
  ('Effia Kwesimitsim', 'Western'),
  ('Effutu Mun.', 'Central'),
  ('Ejisu', 'Ashanti'),
  ('Ejisu-Juaben', 'Ashanti'),
  ('Ejura Sekyedumase', 'Ashanti'),
  ('Ellembele', 'Western'),
  ('Ellembelle', 'Western'),
  ('Ga South', 'Greater Accra'),
  ('Garu', 'Upper East'),
  ('Gomoa East', 'Central'),
  ('Gomoa West', 'Central'),
  ('Guan', 'Oti'),
  ('Ho', 'Volta'),
  ('Ho Mun.', 'Volta'),
  ('Ho West', 'Volta'),
  ('Hohoe', 'Volta'),
  ('Jaman North', 'Bono'),
  ('Jaman South', 'Bono'),
  ('Jasikan', 'Oti'),
  ('Jomoro', 'Western'),
  ('Juaben Municipal', 'Ashanti'),
  ('Juaboso', 'Western North'),
  ('Kaleo Nadowu', 'Upper West'),
  ('Karaga', 'Northern'),
  ('Kassena Nanakana East', 'Upper East'),
  ('Kassena Nankana East', 'Upper East'),
  ('Kassena Nankana Mun.', 'Upper East'),
  ('Keta Mun', 'Volta'),
  ('Kete Krachi', 'Oti'),
  ('Ketu North', 'Volta'),
  ('Kintampo South Mun.', 'Bono East'),
  ('Kpando Municpal', 'Volta'),
  ('Krachi East', 'Oti'),
  ('Krachi Nchumuru', 'Oti'),
  ('Kumasi Metro', 'Ashanti'),
  ('Kumbungu', 'Northern'),
  ('Kwadaso', 'Ashanti'),
  ('Kwaebibrim', 'Eastern'),
  ('Kwahu Afram Plains North', 'Eastern'),
  ('Kwahu East', 'Eastern'),
  ('Kwahu South', 'Eastern'),
  ('La Nkwantanang Mun.', 'Greater Accra'),
  ('La Nkwantanang Municipal', 'Greater Accra'),
  ('Lawra', 'Upper West'),
  ('Ledzokuku', 'Greater Accra'),
  ('Lower Manya Krobo', 'Eastern'),
  ('Mampong', 'Ashanti'),
  ('Mampurugu Moagduri', 'North East'),
  ('Mfantseman', 'Central'),
  ('Mfantsiman', 'Central'),
  ('Mfantsiman Mun', 'Central'),
  ('Nadowli Kaleo', 'Upper West'),
  ('Nandom', 'Upper West'),
  ('Nandom District', 'Upper West'),
  ('New Juaben', 'Eastern'),
  ('New Juaben Mun.', 'Eastern'),
  ('New Juabeng', 'Eastern'),
  ('Ningo Prampram', 'Greater Accra'),
  ('Nkoranza South', 'Bono East'),
  ('Nzema East', 'Western'),
  ('Offinso North', 'Ashanti'),
  ('Ofinso', 'Ashanti'),
  ('Okaikwei South', 'Greater Accra'),
  ('Okere', 'Eastern'),
  ('Okere District', 'Eastern'),
  ('Osu Klottey', 'Greater Accra'),
  ('Saboba', 'Northern'),
  ('Sagnerigu', 'Northern'),
  ('Savelugu Municipal', 'Northern'),
  ('Sawla Tuna Kalba', 'Savannah'),
  ('Sekondi Takoradi Metro', 'Western'),
  ('Sekyere East', 'Ashanti'),
  ('Sekyere Kumawu', 'Ashanti'),
  ('Sekyere South', 'Ashanti'),
  ('Sene East', 'Bono East'),
  ('Shai Osudoku', 'Greater Accra'),
  ('Shama', 'Western'),
  ('Sisala East', 'Upper West'),
  ('South Dayi', 'Volta'),
  ('South Tongu', 'Volta'),
  ('Suhum Mun.', 'Eastern'),
  ('Sunyani Mun', 'Bono'),
  ('Sunyani Municipal', 'Bono'),
  ('Sunyani West', 'Bono'),
  ('Talensi', 'Upper East'),
  ('Tamale Metro', 'Northern'),
  ('Tamale Mun', 'Northern'),
  ('Tano North', 'Ahafo'),
  ('Tano South', 'Ahafo'),
  ('Tatale', 'Northern'),
  ('Techiman', 'Bono East'),
  ('Tema Metro', 'Greater Accra'),
  ('Wa Mun.', 'Upper West'),
  ('Wa Municipal', 'Upper West'),
  ('Wassa Amenfi Central', 'Western'),
  ('Wassa Amenfi East', 'Western'),
  ('Wassa West', 'Western'),
  ('West Akim', 'Eastern'),
  ('West Gonja', 'Savannah'),
  ('West Mampusi', 'North East'),
  ('Yilo Krobo', 'Eastern'),
  ('Zabzugu', 'Northern')
) AS d(district_name, region_name)
JOIN regions r ON r.region_name = d.region_name
ON CONFLICT (district_name, region_id) DO NOTHING;
