-- Seed: institutions
INSERT INTO institutions (institution_name, cssps_code, region_id, district_id, location, institution_type, gender_type)
SELECT i.institution_name, i.cssps_code, r.region_id, d.district_id, i.location, i.institution_type, i.gender_type
FROM (VALUES
  ('TSC Technical Institute, Goaso', '9060400', 'Ahafo', 'Asunafo North', 'Goaso', 'C', 'Mixed'),
  ('Fawohoyeden Technical Institute', '9061400', 'Ahafo', 'Asunafo North', 'Fawohoyeden', 'C', 'Mixed'),
  ('Gyedu Technical Institute', '9062400', 'Ahafo', 'Asutifi North', 'Gyedu', 'C', 'Mixed'),
  ('Bechem Technical Institute', '9060802', 'Ahafo', 'Tano South', 'Bechem', 'B', 'Mixed'),
  ('Yamfo Technical Institute', '9060200', 'Ahafo', 'Tano North', 'Yamfo', 'A', 'Mixed'),
  ('TSC Technical Institute, Bechem', '9060800', 'Ahafo', 'Tano South', 'Bechem', 'C', 'Mixed'),
  ('Akrodie Technical Institute', '9060139', 'Ahafo', 'Asunafo North', 'Akrodie', 'C', 'Mixed'),
  ('Adrobaa Technical Institute', '9060201', 'Ahafo', 'Tano North', 'Adrobaa', 'C', 'Mixed'),
  ('Kwapong Technical Institute', '9063011', 'Ahafo', 'Asunafo South', 'Kwapong', 'C', 'Mixed'),
  ('Islamic Mission Technical Institute', '9060205', 'Ahafo', 'Tano North', 'Duayaw Nkwanta, Koforidua', 'C', 'Mixed'),
  ('Hemang Buoho Technical Institute', '9052000', 'Ashanti', 'Afigya Kwabre South', 'Hemang Buoho', 'C', 'Mixed'),
  ('TSC Technical Institute, Konongo', '9050900', 'Ashanti', 'Asante Akim Central', 'Konongo', 'C', 'Mixed'),
  ('Asankare Technical Institute', '9051300', 'Ashanti', 'Asante Akim South', 'Asankare', 'B', 'Mixed'),
  ('Business Secretarial and Technical Institute', '9050104', 'Ashanti', 'Asokwa', 'Chirapatre', 'C', 'Mixed'),
  ('Nerebehi Technical Institute', '9051400', 'Ashanti', 'Atwim Nwabiagya', 'Nerebehi', 'C', 'Mixed'),
  ('Twedie Technical Institute', '9052300', 'Ashanti', 'Atwima Kwawoma', 'Twedie', 'C', 'Mixed'),
  ('Nana Ampontua Technical Institute', '9050401', 'Ashanti', 'Bekwai Mun.', 'Bekwai', 'C', 'Mixed'),
  ('TSC Technical Institute, Bekwai', '9050402', 'Ashanti', 'Bekwai Mun.', 'Bekwai', 'C', 'Mixed'),
  ('Yaa Pokua Technical Institute', '9057771', 'Ashanti', 'Offinso North', 'Nkekaasu', 'C', 'Mixed'),
  ('Amoafo Technical Institute', '9050403', 'Ashanti', 'Bekwai Mun.', 'Bekwai', 'C', 'Mixed'),
  ('St. Michael''s Technical Institute', '9052800', 'Ashanti', 'Bosomtwe', 'Pramso', 'B', 'Mixed'),
  ('Abosamso Technical Institute', '9053001', 'Ashanti', 'Bosome-Freho', 'Abosamso', 'C', 'Mixed'),
  ('Konkoma Technical Institute', '9052801', 'Ashanti', 'Bosomtwi', 'Konkomba', 'C', 'Mixed'),
  ('Tetrefu Technical Institute', '9052802', 'Ashanti', 'Bosomtwi', 'Tetrefu', 'C', 'Mixed'),
  ('Afoako Technical Institute', '9054012', 'Ashanti', 'Amansie Central', 'Afoako', 'C', 'Mixed'),
  ('Adako Jachie Technical Institute', '9050301', 'Ashanti', 'Ejisu', 'Kwamo', 'A', 'Mixed'),
  ('Ejuraman Technical Institute', '9056014', 'Ashanti', 'Ejura Sekyedumase', 'Ejura', 'C', 'Mixed'),
  ('Baworo Technical Institute', '9050302', 'Ashanti', 'Ejisu', 'Baworo', 'C', 'Mixed'),
  ('Otaakrom Technical Institute', '9055601', 'Ashanti', 'Atwima Mponua', 'Otaakrom', 'C', 'Mixed'),
  ('Kumasi Tech. Inst.', '9050101', 'Ashanti', 'Kumasi Metro', 'Kumasi', 'A', 'Mixed'),
  ('Achiase Technical Institute', '9050312', 'Ashanti', 'Juaben Municipal', 'Achiase', 'C', 'Mixed'),
  ('Akumadan Applied  Technology  Institute', '9057772', 'Ashanti', 'Offinso North', 'Akumadan', 'C', 'Mixed'),
  ('Suntreso Technical Institute', '9050109', 'Ashanti', 'Kumasi Metro', 'North Suntreso', 'C', 'Mixed'),
  ('Suame Technical Institute', '9050103', 'Ashanti', 'Kumasi Metro', 'Suame', 'A', 'Mixed'),
  ('Methodist Technincal  Institute', '9050102', 'Ashanti', 'Kwadaso', 'Kwadaso', 'B', 'Mixed'),
  ('TSC Technical Institute, Mampong', '9050500', 'Ashanti', 'Mampong', 'Mampong', 'C', 'Mixed'),
  ('Offinso Technical Institute', '9050600', 'Ashanti', 'Ofinso', 'Offinso', 'C', 'Mixed'),
  ('Kumawu Technical Institute', '9052900', 'Ashanti', 'Sekyere Kumawu', 'Kumawu', 'C', 'Mixed'),
  ('Krobea Asante Technical and Vocational Institute', '9051801', 'Ashanti', 'Sekyere East', 'Asokore', 'B', 'Mixed'),
  ('Jachie Technical  Institute', '9052803', 'Ashanti', 'Bosomtwe', 'Jachie', 'C', 'Mixed'),
  ('TSC Technical Institute, Sekyere Kumawu', '9053000', 'Ashanti', 'Sekyere Kumawu', 'Sekyere Kumawu', 'C', 'Mixed'),
  ('Agona Technical Institute', '9052701', 'Ashanti', 'Sekyere South', 'Agona Ashanti', 'B', 'Mixed'),
  ('Kokoben Technical Institute', '9050319', 'Ashanti', 'Bosome Freho', 'Asiwa-Kokoben', 'C', 'Mixed'),
  ('Dwease-Praaso Technical Institute', '9051301', 'Ashanti', 'Asante Akyem Central', 'Dwease-Praaso', 'C', 'Mixed'),
  ('Catholic Technical Institute', '9050105', 'Ashanti', 'Kumasi Metro', 'Kumasi', 'C', 'Mixed'),
  ('Ramseyer Technical Institute', '9050112', 'Ashanti', 'Asokwa', 'Asokwa', 'C', 'Mixed'),
  ('Juaben Technical Institute', '9050303', 'Ashanti', 'Ejisu-Juaben', 'Juaben', 'C', 'Mixed'),
  ('Pakyi Applied Technology Institute', '9054022', 'Ashanti', 'Amansie West', 'Pakyi', 'C', 'Mixed'),
  ('TSC Technical Institute, Dormaa Ahenkro', '9061000', 'Bono', 'Dormaa Central Mun', 'Dormaa Ahenkro', 'C', 'Mixed'),
  ('Dormaa Technical Institute', '9061001', 'Bono', 'Dormaa Central', 'Dormaa Ahenkro', 'A', 'Mixed'),
  ('TSC Technical Institute, Drobo', '9060500', 'Bono', 'Jaman South', 'Drobo', 'C', 'Mixed'),
  ('Our Lady of Fatima Technical Institute', '9061100', 'Bono', 'Jaman North', 'Sampa', 'B', 'Mixed'),
  ('Sunyani Technical Institute', '9060106', 'Bono', 'Sunyani Mun', 'Sunyani', 'C', 'Mixed'),
  ('Social Welfare Technical Institute, Sunyani', '9060107', 'Bono', 'Sunyani Mun', 'Sunyani', 'C', 'Mixed'),
  ('Sunyani Methodist Technical Inst.', '9060101', 'Bono', 'Sunyani Municipal', 'Sunyani', 'C', 'Mixed'),
  ('Don Bosco Voc./Tech. Inst.', '9062601', 'Bono', 'Sunyani West', 'Odumase', 'B', 'Mixed'),
  ('Nsoatre Technical Institute', '9062602', 'Bono', 'Sunyani West', 'Nsoatre', 'B', 'Mixed'),
  ('Nkwabeng Technical Institute', '9060905', 'Bono East', 'Nkoranza South', 'Nkwabeng', 'C', 'Mixed'),
  ('Kintampo Technical Institute', '9060301', 'Bono East', 'Kintampo South Mun.', 'Kintampo', 'C', 'Mixed'),
  ('Nkoranza Tech Inst.', '9060901', 'Bono East', 'Nkoranza South', 'Nkoranza', 'A', 'Mixed'),
  ('Techiman Technical Institute', '9061200', 'Bono East', 'Techiman', 'Techiman', 'C', 'Mixed'),
  ('Kajaji Technical Institute', '9067793', 'Bono East', 'Sene East', 'Kajaji', 'C', 'Mixed'),
  ('Asuansi Tech. Inst.', '9030401', 'Central', 'Abura/Asebu/kwamankese', 'Asuansi', 'A', 'Mixed'),
  ('Agona Swedru Technical Institute', '9031101', 'Central', 'Agona West Mun.', 'Agona Swedru', 'B', 'Mixed'),
  ('Ajumako-Afranse Technical Institute', '9030802', 'Central', 'Ajumako Enyan Esiam', 'Ajumako', 'C', 'Mixed'),
  ('Enyan-Abaasa Technical Institute', '9030801', 'Central', 'Ajumako/ Enyan /Essiam', 'Enyan Abaasa', 'B', 'Mixed'),
  ('Breman Asikuma Technical Institute', '9031300', 'Central', 'Asikuma Odoben Brakwa', 'Breman-Asikuma', 'C', 'Mixed'),
  ('TSC Technical Institute, Assin Edubiase', '9030700', 'Central', 'Assin Central Mun.', 'Assin Edubiase', 'C', 'Mixed'),
  ('Assin Foso Technical Institute', '9030701', 'Central', 'Assin North', 'Assin Fosu', 'A', 'Mixed'),
  ('TSC Technical Institute, Awutu Breku', '9031200', 'Central', 'Awutu Senya West', 'Awutu Senya', 'C', 'Mixed'),
  ('Cape Coast Tech. Inst.', '9030101', 'Central', 'Cape Coast Metro', 'Cape Coast', 'A', 'Mixed'),
  ('GRATIS Technical Institute, Cape Coast', '9030102', 'Central', 'Cape Coast Mun', 'Cape Coast', 'C', 'Mixed'),
  ('Social Welfare Girls'' Technical Institute, Pedu', '9030103', 'Central', 'Cape Coast Mun', 'Pedu', 'C', 'Girls'),
  ('Winneba Technical Institute', '9030900', 'Central', 'Effutu Mun.', 'Winneba', 'A', 'Mixed'),
  ('Panfokrom Technical Institute', '9030601', 'Central', 'Gomoa East', 'Panfokrom', 'A', 'Mixed'),
  ('Gomoa Adaa Technical Institute', '9030500', 'Central', 'Gomoa West', 'Gomoa Adaa', 'B', 'Mixed'),
  ('Mankessim Technical Institute', '9030300', 'Central', 'Mfantsiman', 'Mankessim', 'C', 'Mixed'),
  ('New Ebu Technical Institute', '9030414', 'Central', 'Abura Asebu Kwamankese', 'New Ebu', 'C', 'Mixed'),
  ('Biriwa Technical Institute', '9030301', 'Central', 'Mfantsiman Mun', 'Biriwa', 'A', 'Mixed'),
  ('Asafora Technical Institute', '9030321', 'Central', 'Mfantseman', 'Asafora', 'C', 'Mixed'),
  ('Assin Jakai Applied Technology Institute', '9030707', 'Central', 'Assin Jakai', 'Assin South', 'C', 'Mixed'),
  ('J.G. Knol Technical Instititute', '9021601', 'Eastern', 'Okere District', 'Adukrom Akuapem', 'C', 'Mixed'),
  ('Akrofufu Technical Institute', '9022200', 'Eastern', 'Atiwa West', 'Akrofufu', 'C', 'Mixed'),
  ('Anum Presbyterian Technical Institute', '9020800', 'Eastern', 'Asuogyaman', 'Anum', 'B', 'Mixed'),
  ('Akwatia Tech. Inst.', '9021101', 'Eastern', 'Denkyembour', 'Akwatia', 'A', 'Mixed'),
  ('Kibi Technical Institute', '9021302', 'Eastern', 'Eask Akim Mun.', 'Kibi', 'A', 'Mixed'),
  ('St. Paul''s Tech. Inst.', '9021301', 'Eastern', 'East Akim', 'Kukurantumi', 'A', 'Mixed'),
  ('Takrowase Technical Institute', '9022600', 'Eastern', 'Kwaebibrim', 'Takrowasi', 'C', 'Mixed'),
  ('Amankwakrom Fisheries Agric. Tech. Inst.', '9020901', 'Eastern', 'Kwahu Afram Plains North', 'Amankwakrom', 'B', 'Mixed'),
  ('St. Mary''s Voc./Tech. Inst.', '9020902', 'Eastern', 'Kwahu Afram Plains North', 'Adiembra', 'C', 'Girls'),
  ('TSC Technical Institute, Donkorkrom', '9020903', 'Eastern', 'Kwahu Afram Plains North', 'Donkorkrom', 'C', 'Mixed'),
  ('St. Joseph''s Tech. Inst.', '9022001', 'Eastern', 'Kwahu East', 'Kwahu Tafo', 'B', 'Mixed'),
  ('Abetifi Tech. Inst.', '9021001', 'Eastern', 'Kwahu East', 'Abetifi', 'B', 'Mixed'),
  ('Abetifi Kyemase Technical  Institute', '9021002', 'Eastern', 'Kwahu East', 'Abetifi', 'A', 'Mixed'),
  ('Kpong Technical Institute', '9021502', 'Eastern', 'Lower Manya Krobo', 'Kpong', 'C', 'Mixed'),
  ('Koforidua GRATIS Technical Institute', '9020104', 'Eastern', 'New Juaben', 'Koforidua', 'C', 'Mixed'),
  ('Koforidua Tech. Inst.', '9020101', 'Eastern', 'New Juaben Mun.', 'Koforidua', 'A', 'Mixed'),
  ('Effiduase Technical Institute', '9020102', 'Eastern', 'New Juabeng', 'Effiduase-Koforidua', 'C', 'Mixed'),
  ('Abiriw Presbyterian Technical Institute', '9021602', 'Eastern', 'Okere', 'Abiriw', 'C', 'Mixed'),
  ('Akuapem Technical Institute', '9020301', 'Eastern', 'Akwapem South', 'Kitase-Aburi', 'C', 'Mixed'),
  ('Suhum Technical Institute', '9020701', 'Eastern', 'Suhum Mun.', 'Suhum', 'B', 'Mixed'),
  ('St. Mary''s Technical Institute, Asamankese', '9020500', 'Eastern', 'West Akim', 'Asamankese', 'A', 'Mixed'),
  ('TSC Technical Institute, Asamankese', '9020501', 'Eastern', 'West Akim', 'Asamankese', 'C', 'Mixed'),
  ('Denkyembour Technical Institute', '9021105', 'Eastern', 'Denkyembour', 'Boadua', 'C', 'Mixed'),
  ('Asakraka Technical Institute', '9022301', 'Eastern', 'Kwahu South', 'Asakraka', 'C', 'Mixed'),
  ('Somanya Technical Institute', '9021401', 'Eastern', 'Yilo Krobo', 'Somanya', 'C', 'Mixed'),
  ('Tutu Methodist Technical Institute', '9021603', 'Eastern', 'Akuampem North', 'Tutu', 'C', 'Mixed'),
  ('Applied Technology Institute - Anyinam', '9022201', 'Eastern', 'Atiwa East', 'Anyinam', 'C', 'Mixed'),
  ('New Century Technical Institute', '9010104', 'Greater Accra', 'Ablekuma West', 'Dansoman', 'A', 'Mixed'),
  ('Sacred Heart Tech. Inst.', '9010102', 'Greater Accra', 'Accra Metro', 'Jamsetown', 'B', 'Mixed'),
  ('Ada Tech. Inst.', '9011601', 'Greater Accra', 'Ada East', 'Ada', 'A', 'Mixed'),
  ('Ashiaman Technical Institute', '9011001', 'Greater Accra', 'Ashiaman Mun', 'Ashaiman', 'C', 'Mixed'),
  ('Opportunities Industrialization Technical Institute, Accra', '9010123', 'Greater Accra', 'Ayawaso', 'East Legon', 'C', 'Mixed'),
  ('Pilot Technical Institute', '9010105', 'Greater Accra', 'Ayawaso Central', 'Kokomlemle', 'A', 'Mixed'),
  ('Kanda Technical Institute', '9010106', 'Greater Accra', 'Ayawaso East', 'Kanda', 'C', 'Mixed'),
  ('Accra Tech. Trg. Centre', '9010101', 'Greater Accra', 'Ayawaso South', 'Kokomlemle', 'A', 'Mixed'),
  ('Bedeku Technical Institute', '9010500', 'Greater Accra', 'Ada East', 'Bedeku', 'C', 'Mixed'),
  ('Ngleshie Amanfro Technical Institute', '9011302', 'Greater Accra', 'Ga South', 'Ngleshie Amanfro', 'C', 'Mixed'),
  ('Madina Technical Institute', '9010901', 'Greater Accra', 'La Nkwantanang Mun.', 'Madin', 'A', 'Mixed'),
  ('Teshie Tech. Instittute', '9011701', 'Greater Accra', 'Ledzokuku', 'Teshie', 'C', 'Mixed'),
  ('Afienya  Technical Institute', '9010602', 'Greater Accra', 'Ningo Prampram', 'Afienya', 'B', 'Mixed'),
  ('Prampram Technical Institute', '9010601', 'Greater Accra', 'Ningo Prampram', 'Prampram', 'C', 'Mixed'),
  ('South Labone Girls Technical Institute', '9010107', 'Greater Accra', 'Osu Klottey', 'Labone', 'C', 'Girls'),
  ('Agomeda Technical Institute', '9010702', 'Greater Accra', 'Shai Osudoku', 'Agomeda', 'C', 'Mixed'),
  ('Dodowa Technical Institute', '9010700', 'Greater Accra', 'Shai Osudoku', 'Dodowa', 'C', 'Mixed'),
  ('Tema Tech. Inst.', '9010201', 'Greater Accra', 'Tema Metro', 'Tema', 'A', 'Mixed'),
  ('Tema Mission Technical Institute', '9010206', 'Greater Accra', 'Tema Metro', 'Tema', 'A', 'Mixed'),
  ('Government Technical Institute', '9010108', 'Greater Accra', 'Okaikwei South', 'Kaneshie-Accra', 'B', 'Mixed'),
  ('Danfa Technical Institute', '9010906', 'Greater Accra', 'La Nkwantanang Municipal', 'Danfa', 'C', 'Mixed'),
  ('Nima Technical Institute', '9010112', 'Greater Accra', 'Ayawaso East Sub Metro', 'Nima', 'C', 'Mixed'),
  ('East Legon Applied Technology Institute', '9011400', 'Greater Accra', 'Accra Metro', 'East Legon', 'A', 'Mixed'),
  ('Nalerigu Technical Institute', '9081000', 'North East', 'East Mamprusi', 'Nalerigu', 'C', 'Mixed'),
  ('Walewale Technical Institute', '9080601', 'North East', 'West Mampusi', 'Walawale', 'C', 'Mixed'),
  ('Loagri Technical Institute', '9080701', 'North East', 'Mampurugu Moagduri', 'Loagri', 'C', 'Mixed'),
  ('Zugu Dabogni Technical Institute', '9081600', 'Northern', 'Kumbungu', 'Zugu Dabogni', 'C', 'Mixed'),
  ('Tamale Technical Institute', '9081901', 'Northern', 'Sagnerigu', 'Tamale', 'C', 'Mixed'),
  ('Gbewa Technical Institute', '9080110', 'Northern', 'Tamale Metro', 'Tamale', 'C', 'Mixed'),
  ('St. Joseph''s Tech. Inst., Saboba', '9080901', 'Northern', 'Saboba', 'Saboba', 'B', 'Mixed'),
  ('Dabokpa Voc/Tech. Inst.', '9080101', 'Northern', 'Tamale Metro', 'Tamale', 'A', 'Mixed'),
  ('St. Mary''s Technical Institute,Tamale', '9080102', 'Northern', 'Tamale Metro', 'Tamale', 'C', 'Girls'),
  ('Lamashegu Technical Institute', '9080103', 'Northern', 'Tamale Metro', 'Tamale', 'C', 'Mixed'),
  ('Kumbungu Vocational Techncal Institute', '9087782', 'Northern', 'Kumbungu', 'Kumbungu', 'C', 'Mixed'),
  ('GRATIS Technical Institute, Tamale', '9080104', 'Northern', 'Tamale Metro', 'Tamale', 'C', 'Mixed'),
  ('Nyohini Community Technical Institute', '9080105', 'Northern', 'Tamale Mun', 'Tamale', 'C', 'Mixed'),
  ('Tatale Technical Institute', '9082045', 'Northern', 'Tatale', 'Tatale', 'C', 'Mixed'),
  ('Zabzugu Technical Institute', '9081606', 'Northern', 'Zabzugu', 'Zabzugu', 'C', 'Mixed'),
  ('Kofi Annan Technical Institute', '9081601', 'Northern', 'Kumbungu', 'Nwodua', 'C', 'Mixed'),
  ('Nyong Technical Institute', '9080301', 'Northern', 'Karaga', 'Nyong', 'C', 'Mixed'),
  ('Savelugu Technical Institute', '9081903', 'Northern', 'Savelugu Municipal', 'Savelugu', 'C', 'Mixed'),
  ('Fr. Dogli Memorial Technical Institute', '9070401', 'Oti', 'Jasikan', 'New Ayoma', 'C', 'Mixed'),
  ('Kaakyi Technical Institute', '9072001', 'Oti', 'Kete Krachi', 'Kete Krachi', 'C', 'Mixed'),
  ('St Theresa''s Technical Institute', '9070800', 'Oti', 'Krachi Nchumuru', 'Chinderi', 'C', 'Mixed'),
  ('Lolobi Technical Institute', '9072112', 'Oti', 'Guan', 'Lolobi Ashiambi', 'C', 'Mixed'),
  ('Dambai Technical Institute', '9073012', 'Oti', 'Krachi East', 'Dambai', 'C', 'Mixed'),
  ('Bole Technical Institute', '9080700', 'Savannah', 'Bole', 'Bole', 'C', 'Mixed'),
  ('Buipe Technical Institute', '9081501', 'Savannah', 'Central Gonja', 'Buipe', 'C', 'Mixed'),
  ('Sawla Girls Vocational Institute', '9080655', 'Savannah', 'Sawla Tuna Kalba', 'Sawla', 'C', 'Girls'),
  ('Salaga Technical Institute', '9081500', 'Savannah', 'East Gonja', 'Salaga', 'C', 'Mixed'),
  ('Damongo Technical Institute', '9082100', 'Savannah', 'West Gonja', 'Damongo', 'C', 'Mixed'),
  ('Bawku Tech. Inst.', '9090101', 'Upper East', 'Bawku East', 'Bawku', 'A', 'Mixed'),
  ('Kpalwega Technical Institute', '9090102', 'Upper East', 'Bawku East', 'Bawku', 'C', 'Mixed'),
  ('Kusanaba Technical Institute', '9090600', 'Upper East', 'Bawku West Mun.', 'Binaba', 'B', 'Mixed'),
  ('Bolga Tech. Inst.', '9090401', 'Upper East', 'Bolgatanga', 'Bolgatanga', 'A', 'Mixed'),
  ('Bolgatanga Central Technical Institute', '9090403', 'Upper East', 'Bolgatanga Mun', 'Bolgatanga', 'C', 'Mixed'),
  ('GRATIS Technical Institute, Bolga', '9090402', 'Upper East', 'Bolgatanga Mun', 'Bolgatanga', 'C', 'Mixed'),
  ('Bongo Technical Institute', '9090701', 'Upper East', 'Bongo', 'Bongo', 'C', 'Mixed'),
  ('Sandema Technical Institute', '9091000', 'Upper East', 'Builsa North', 'Sandema', 'C', 'Mixed'),
  ('TSC Technical Institute - Garu', '9090800', 'Upper East', 'Garu', 'Garu', 'C', 'Mixed'),
  ('St. Bernadettes Tech/Voc. Institute', '9090901', 'Upper East', 'Kassena Nanakana East', 'Navrongo', 'C', 'Mixed'),
  ('TSC Technical Institute -Kassena Nankana', '9090903', 'Upper East', 'Kassena Nankana East', '', 'C', 'Mixed'),
  ('Nabango Technical Institute', '9095606', 'Upper East', 'Kassena Nankana East', 'Nabango', 'C', 'Mixed'),
  ('Navrongo Technical Institute', '9090902', 'Upper East', 'Kassena Nankana Mun.', 'Navrongo', 'C', 'Mixed'),
  ('Namalteng Technical Institute', '9091200', 'Upper East', 'Talensi', 'Gbeogo Namalteng', 'C', 'Mixed'),
  ('Issa Technical Institute', '9100800', 'Upper West', 'Dafiama Busie Issa', 'Issa', 'C', 'Mixed'),
  ('St. Basilides Voc./Tech. Inst.', '9101001', 'Upper West', 'Nadowli Kaleo', 'Kaleo', 'B', 'Mixed'),
  ('TSC Technical Institute, Nadowli - Kaleo', '9101002', 'Upper West', 'Nadowli Kaleo', 'Nadowli', 'C', 'Mixed'),
  ('St. John''s Voc. Tech. Institute', '9100901', 'Upper West', 'Nandom', 'Nandom', 'B', 'Mixed'),
  ('St Anne''s Vocational Training Institute', '9100902', 'Upper West', 'Nandom', 'Nandom', 'B', 'Girls'),
  ('St. Clare''s Technical Institute', '9100400', 'Upper West', 'Sisala East', 'Tumu', 'C', 'Mixed'),
  ('GRATIS Technical Institute, Wa', '9100103', 'Upper West', 'Wa Mun.', 'Wa', 'C', 'Mixed'),
  ('Naa-Momori Technical Institute', '9100104', 'Upper West', 'Wa Mun.', 'Wa', 'C', 'Mixed'),
  ('Tibani Technical Institute', '9100415', 'Upper West', 'Kaleo Nadowu', 'Tibani', 'C', 'Mixed'),
  ('Birifo Technical Institute', '9100741', 'Upper West', 'Lawra', 'Birifo', 'C', 'Mixed'),
  ('Wa Tech. Inst.', '9100101', 'Upper West', 'Wa Municipal', 'Wa', 'A', 'Mixed'),
  ('Nakori Chansa Technical Institute', '9100102', 'Upper West', 'Wa Municipal', 'Wa', 'C', 'Mixed'),
  ('Guo Technical Insititute', '9101103', 'Upper West', 'Nandom District', 'Guo', 'C', 'Mixed'),
  ('St. Daniel Comboni Technical Institute', '9072101', 'Volta', 'Afadzto South', 'Liati', 'B', 'Mixed'),
  ('Have Tech. Inst.', '9072100', 'Volta', 'Afadzto South', 'Have', 'B', 'Mixed'),
  ('Avenorpeme Technical Institute', '9072400', 'Volta', 'Akatsi South', 'Avenorpeme', 'C', 'Mixed'),
  ('Ve- Golokwati Technical Institute', '9071014', 'Volta', 'Afadzto South', 'Kwati', 'C', 'Mixed'),
  ('Avenui-Awudome Technical Institute', '9070150', 'Volta', 'Ho West', 'Avenui-Awudome', 'C', 'Mixed'),
  ('Ave Technical Institute', '9072401', 'Volta', 'Akatsi North', 'Ave', 'C', 'Mixed'),
  ('Volta Tech Inst', '9070702', 'Volta', 'Ho', 'Matse', 'C', 'Mixed'),
  ('Ho -Lokoe Technical Institute', '9070704', 'Volta', 'Ho Mun.', 'Ho', 'C', 'Mixed'),
  ('Ho Technical Institute', '9070703', 'Volta', 'Ho Mun.', 'Ho', 'C', 'Mixed'),
  ('Amedzofe Technical Institute', '9070101', 'Volta', 'Ho West', 'Amedzofe', 'C', 'Mixed'),
  ('Tsibu Technical Institute', '9070113', 'Volta', 'Ho West', 'Tsibu Awodume', 'C', 'Mixed'),
  ('E.P. Tech/Voc Inst', '9071002', 'Volta', 'Hohoe', 'Alavanyo', 'C', 'Mixed'),
  ('Anlo Tech. Inst.', '9070501', 'Volta', 'Anloga Municipal', 'Anloga', 'A', 'Mixed'),
  ('Caring Sisters Technical Institute', '9070503', 'Volta', 'Anloga Municipal', 'Tegbi', 'C', 'Mixed'),
  ('Atorkor Technical Institute', '9070500', 'Volta', 'Keta Mun', 'Atorkor', 'C', 'Mixed'),
  ('Kedzi Technical Institute', '9070514', 'Volta', 'Keta Mun', 'Kedzi', 'C', 'Mixed'),
  ('Kpando Tech. Inst.', '9070601', 'Volta', 'Kpando Municpal', 'Kpando', 'A', 'Mixed'),
  ('C.Y.O. Tech/Voc. Inst.', '9070602', 'Volta', 'Kpando Municpal', 'Sovie', 'C', 'Mixed'),
  ('Toh-Kpalime Technical Institute', '9071200', 'Volta', 'South Dayi', 'Toh-Kpalime', 'C', 'Mixed'),
  ('Comboni Tech/Voc Inst.', '9070901', 'Volta', 'South Tongu', 'Sogakope', 'B', 'Mixed'),
  ('Klefe Technical Institute', '9070705', 'Volta', 'Ho Mun.', 'Klefe', 'C', 'Mixed'),
  ('Dzodze Technical Institute', '9070710', 'Volta', 'Ketu North', 'Dzodze', 'C', 'Mixed'),
  ('Sogakope Technial Institute', '9071904', 'Volta', 'South Tongu', 'Sogakope', 'C', 'Mixed'),
  ('Botoku Technical Insitute', '9071201', 'Volta', 'Dayi', 'Botoku', 'C', 'Mixed'),
  ('Woe Technical Institute', '9070515', 'Volta', 'Keta Mun', 'Woe', 'C', 'Mixed'),
  ('Anfoeta Technical Institute', '9070155', 'Volta', 'Ho West', 'Anfoeta Gborgame', 'C', 'Mixed'),
  ('TSC Technical Institute - Asankragwa', '9041300', 'Western', 'Amenfi West', 'Asankragwa', 'C', 'Mixed'),
  ('Takoradi Tech. Inst.', '9040101', 'Western', 'Effia Kwesimitsim', 'Takoradi', 'A', 'Mixed'),
  ('Takoradi Community Technical Institute', '9040107', 'Western', 'Effia Kwesimitsim', 'Anaji', 'C', 'Mixed'),
  ('Charlotte Dolphyne Technical Institute', '9040402', 'Western', 'Ellembele', 'Sanzule', 'B', 'Mixed'),
  ('Kikam Tech. Inst.', '9040401', 'Western', 'Ellembelle', 'Kikam', 'A', 'Mixed'),
  ('Asasetre Technical Institute', '9040415', 'Western', 'Ellembelle', 'Asasetre', 'C', 'Mixed'),
  ('TSC Technical Institute - Half Assini', '9040700', 'Western', 'Jomoro', 'Half Assini', 'C', 'Mixed'),
  ('Axim Technical Institute', '9040301', 'Western', 'Nzema East', 'Axim', 'B', 'Mixed'),
  ('Sekondi Takoradi Technical Institute', '9040102', 'Western', 'Sekondi Takoradi Metro', 'Takoradi', 'B', 'Mixed'),
  ('Opportunities Industralisation Technical Institute - Takoradi', '9040105', 'Western', 'Sekondi Takoradi Metro', 'Takoradi', 'C', 'Mixed'),
  ('Essipun Technical Institute', '9040106', 'Western', 'Sekondi Takoradi Metro', 'Essipun Sekondi', 'C', 'Mixed'),
  ('Shama Technical Institute', '9041100', 'Western', 'Shama', 'Shama', 'C', 'Mixed'),
  ('Manso-Amenfi Technical Institute', '9041200', 'Western', 'Wassa Amenfi Central', 'Manso Amenfi', 'C', 'Mixed'),
  ('Tarkwa Technical Institute', '9040201', 'Western', 'Wassa West', 'Tarkwa', 'B', 'Mixed'),
  ('Mesu Akompi Technical Institute', '9041412', 'Western', 'Wassa Amenfi East', 'Wassa Saa', 'C', 'Mixed'),
  ('Abura Technical Institute', '9040800', 'Western', 'Ahanta West', 'Abura', 'C', 'Mixed'),
  ('St. Ann''s Technical Institute', '9041201', 'Western', 'Sekondi Takoradi Metro', 'Sekondi', 'C', 'Girls'),
  ('Libermann Technical Institute', '9040705', 'Western', 'Jomoro', 'Sowodadzem', 'C', 'Mixed'),
  ('Sekondi Technical Institute', '9040108', 'Western', 'Sekondi Takoradi Metro', 'Sekondi', 'C', 'Mixed'),
  ('TSC Technical Institute - Bibiani', '9040600', 'Western North', 'Bibiani Anhwiaso Bekwai', 'Bibiani', 'C', 'Mixed'),
  ('Bonso Nkwanta Technical Institute', '9040901', 'Western North', 'Juaboso', 'Bonsu Nkwanta', 'C', 'Mixed')
) AS i(institution_name, cssps_code, region_name, district_name, location, institution_type, gender_type)
JOIN regions r ON r.region_name = i.region_name
LEFT JOIN districts d ON d.district_name = i.district_name AND d.region_id = r.region_id
ON CONFLICT (cssps_code) DO NOTHING;
